compile:
	javac -d . -cp .:../../../../dist/solr-core-5.1.0.jar:../../../../dist/solr-solrj-5.1.0.jar:../../../solr-webapp/webapp/WEB-INF/lib/lucene-core-5.1.0.jar:../../../solr-webapp/webapp/WEB-INF/lib/lucene-analyzers-common-5.1.0.jar *.java
	jar cf PayloadFactory.jar payloadexample/*